### ISSUE TITLE
address mapping problem in hwarch.html

### ISSUE THREAD

**Issue by xranger** [nvdla/nvdla.github.io#1]
The address mapping in nvdla.github.io-master/hwarch.html#address-space-layout seems a lot of mis-match. 
1). Why each block has a 0x3000 offset compare to Table-10? 
2). Table-15 and Table-16 is the same? Should not be, right?

**Comment by jwise** [comment]
Good catch.  I think the first part is the same problem as nvdla/doc#4.  I'll poke the reviewer on that change again :-)

The address offset on table 16 should be different, as you noted; @cliffgold fixed that, too.

I'll close this as a duplicate of that bug, but thank you for sending this in!

**Comment by HippieSavag3** [comment]
Wtf
